# Use new trusty images, should yield newer compilers and packages
dist: trusty
language: c
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
          - COMPILERC=gcc-4.9
          - INSTALL_DIR=${HOME}/pscom_build
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
          - COMPILERC=gcc-5
          - INSTALL_DIR=${HOME}/pscom_build
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
          - COMPILERC=gcc-6
          - INSTALL_DIR=${HOME}/pscom_build

before_install:
    - travis_retry sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
    - travis_retry sudo apt-get -qq update -y
    - sudo apt-get install libpopt-dev libncurses5-dev libreadline-dev libmosquitto-dev libssl-dev libc-ares-dev

script:
    - mkdir build
    - cd build
    - CC=${COMPILERC} ../configure --prefix=${INSTALL_DIR}
    - make
    - make install

#notifications:
#  recipients:
#    test@test.de
#  email:
#    on_success: change
#    on_failure: always
